arch:
    max_epochs: 20
model:
    checkpoint_path: '/home/users/vbelissen/saved_models_v3/default_config-clean_test1-Big-allCams-fromCam0-from13cam0-2021.07.26-09h27m10s/epoch=02_valeo_multiview-list_frames_all_cams_annotated_test_sync_shuffled-velodyne-mixed-abs_rel=0.358.ckpt'
    loss:
        automask_loss: True
        photometric_reduce_op: 'min'
        mask_ego: True
        mask_occlusion: False
        mask_disocclusion: False
        mask_spatial_context: False
        mask_temporal_context: False
        mult_margin_occlusion: 1.5
        add_margin_occlusion: 1.5
        depth_consistency_weight: 0.0
        allow_context_rotation: False
    name: 'SelfSupModel_fisheye'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.00005
        pose:
            lr: 0.00005
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 1
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_train_shuffled.txt']
        depth_type: ['']
        cameras: [['mixed']]
        repeat: [1]
        with_geometric_context: True
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v3' # Where the models will be saved
    monitor: 'abs_rel' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
