arch:
    max_epochs: 20
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.00009
        pose:
            lr: 0.00009
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 150.0
datasets:
    augmentation:
        image_shape: (480, 640)
    train:
        batch_size: 2
        dataset: ['KITTIValeo']
        path: ['/data/vbelissen/valeo_data_ready2train/data']
        split: ['nurstutt_train_perspective_shuffled_20000.txt']
        depth_type: ['']
        cameras: [['Front']]
        repeat: [2]
    validation:
        dataset: ['KITTIValeo']
        path: ['/data/vbelissen/valeo_data_ready2train/data']
        split: ['valeo_test_sync_perspective_shuffled.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTIValeo']
        path: ['/data/vbelissen/valeo_data_ready2train/data']
        split: ['valeo_test_sync_perspective_shuffled.txt']
        depth_type: ['velodyne']
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models' # Where the models will be saved
    monitor: 'abs_rel_pp_gt' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
