arch:
    max_epochs: 20
model:
    checkpoint_path: '/home/users/vbelissen/saved_models/default_config-config0bis_dataValeo_fisheye_far_resnet18_fromDDAD_camFisheyeKnown-Copy1-2021.04.16-08h55m58s/epoch=01_KITTI_tiny-kitti_tiny-velodyne-abs_rel_pp_gt=3.005.ckpt'
    name: 'SelfSupModel_fisheye_valeo'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 150.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 2
        dataset: ['KITTIValeoFisheye']
        path: ['/data/vbelissen/valeo_data_ready2train/data']
        split: ['nurstutt_small_fisheye_train_shuffled.txt']
        depth_type: ['']
        cameras: [['Front']]
        repeat: [4]
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/data/vbelissen/valeo_data_ready2train/data']
        split: ['valeo_test_sync_fisheye.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/data/vbelissen/valeo_data_ready2train/data']
        split: ['valeo_test_sync_fisheye.txt']
        depth_type: ['velodyne']
        cameras: [['Front']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models' # Where the models will be saved
    monitor: 'abs_rel_pp_gt' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
