arch:
    max_epochs: 20
model:
    checkpoint_path: '/home/data/vbelissen/temp_saved_models/default_config-fisheye_v2_config13-cam0-2021.06.26-15h24m33s/epoch=10_valeo_multiview-list_cam_0_annotated_frames_test_sync_shuffled-velodyne-cam_0-abs_rel=0.281.ckpt'
    loss:
        automask_loss: True
        photometric_reduce_op: 'min'
        mask_occlusion: False
        mask_disocclusion: True
        mask_spatial_context: True
        mask_temporal_context: False
        occ_disocc_handling: 'masks'
    name: 'SelfSupModel_fisheye_valeo_testPose3_contextDepth'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 1
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_train_shuffled.txt']
        depth_type: ['']
        cameras: [['mixed']]
        repeat: [1]
        with_geometric_context: True
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v3' # Where the models will be saved
    monitor: 'abs_rel' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
