arch:
    max_epochs: 30
model:
    name: 'SelfSupModel_DGPValeo'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 200.0
datasets:
    augmentation:
        image_shape: (384, 640)
    train:
        batch_size: 1
        dataset: ['DGPvaleo']
        path: ['/home/data/vbelissen/datasets/ddad_train_val/ddad.json']
        split: ['train']
        depth_type: ['lidar']
        cameras: [['camera_01']]
        repeat: [10]
        with_geometric_context: True
    validation:
        dataset: ['DGPvaleo']
        path: ['/home/data/vbelissen/datasets/ddad_train_val/ddad.json']
        split: ['val']
        depth_type: ['lidar']
        cameras: [['camera_01']]
    test:
        dataset: ['DGPvaleo']
        path: ['/home/data/vbelissen/datasets/ddad_train_val/ddad.json']
        split: ['val']
        depth_type: ['lidar']
        cameras: [['camera_01']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_ddad' # Where the models will be saved
    monitor: 'abs_rel_gt' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
