arch:
    max_epochs: 10
model:
    checkpoint_path: '/home/users/vbelissen/saved_models_v4/default_config-F-A-auto-geoContext-recalibrated1-from1024-2021.10.28-08h51m26s/epoch=29_valeo_multiview-list_cam_0_frames_camera0annotated_test_sync_dataset2viewsUS-velodyne-cam_0-abs_rel=0.202.ckpt'
    loss:
        mask_ego: True
    name: 'SelfSupModel_fisheye'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 1
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_camera0annotated_train_shuffled.txt']
        depth_type: ['']
        cameras: [['cam_0']]
        repeat: [1]
        with_geometric_context: True
        calibrations_suffix: '_1'
        depth_suffix: '_1'
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_camera0annotated_test_sync_dataset2viewsUS.txt']
        depth_type: ['velodyne']
        cameras: [['cam_0']]
        calibrations_suffix: '_1'
        depth_suffix: '_1'
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_camera0annotated_test_sync_dataset2viewsUS.txt']
        depth_type: ['velodyne']
        cameras: [['cam_0']]
        calibrations_suffix: '_1'
        depth_suffix: '_1'
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v4' # Where the models will be saved
    monitor: 'abs_rel' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
