arch:
    max_epochs: 30
model:
    checkpoint_path: '/home/users/vbelissen/saved_models_v4/default_config-F-A-auto-geoContext-small-mean-fromRecalib-2021.10.26-16h12m07s/epoch=02_valeo_multiview-list_cam_0_frames_camera0annotated_test_sync_dataset2viewsUS-velodyne-cam_0-abs_rel=0.397.ckpt'
    loss:
        mask_ego: True
    name: 'SelfSupModel_fisheye'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (160, 256)
    train:
        batch_size: 32
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_camera0annotated_train_shuffled.txt']
        depth_type: ['']
        cameras: [['cam_0']]
        repeat: [1]
        with_geometric_context: True
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_camera0annotated_test_sync_dataset2viewsUS.txt']
        depth_type: ['velodyne']
        cameras: [['cam_0']]
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_camera0annotated_test_sync_dataset2viewsUS.txt']
        depth_type: ['velodyne']
        cameras: [['cam_0']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v4' # Where the models will be saved
    monitor: 'abs_rel' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
