arch:
    max_epochs: 30
model:
    checkpoint_path: '/home/users/vbelissen/saved_models_distorted/default_config-distorted-smaller-2021.10.15-20h52m36s/epoch=01_valeo_multiview-list_cam_4_frames_camera4annotated_test_sync_shuffled_dataset2viewsUS-velodyne-cam_4-abs_rel_gt=0.232.ckpt'
    loss:
        mask_ego: True
    name: 'SelfSupModel_fisheye_valeo'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 2
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_camera0annotated_train_shuffled_dataset45views.txt']
        depth_type: ['']
        cameras: [['cam_0']]
        repeat: [1]
        with_geometric_context: False
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_camera0annotated_test_sync_dataset2viewsUS.txt']
        depth_type: ['velodyne']
        cameras: [['cam_0']]
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_camera0annotated_test_sync_dataset2viewsUS.txt']
        depth_type: ['velodyne']
        cameras: [['cam_0']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v4' # Where the models will be saved
    monitor: 'abs_rel_gt' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
