arch:
    max_epochs: 30
model:
    checkpoint_path: '/home/users/vbelissen/saved_models_v3/default_config-fisheye_v2_config51ps-Copy1-2021.06.14-22h30m48s/epoch=00_valeo_multiview-list_frames_all_cams_annotated_test_sync_shuffled-velodyne-mixed-abs_rel=0.241.ckpt'
    loss:
        supervised_method: 'sparse-abs_rel'
        mask_ego: True
        supervised_loss_weight: 0.005
    name: 'SemiSupModel_fisheye_valeo'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNetSlim01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 1
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_train_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
        repeat: [1]
        with_geometric_context: False
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v3' # Where the models will be saved
    monitor: 'abs_rel' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
