arch:
    max_epochs: 20
model:
    checkpoint_path: '/home/users/vbelissen/saved_models_v3/default_config-fisheye_v2_config13-cam0-small-2021.06.18-18h48m49s/epoch=19_valeo_multiview-list_cam_0_annotated_frames_test_sync_shuffled-velodyne-cam_0-abs_rel=0.422.ckpt'
    loss:
        automask_loss: True
        photometric_reduce_op: 'min'
        mask_ego: True
    name: 'SelfSupModel_fisheye_valeo_testPose3'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 1
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_train_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
        repeat: [1]
        with_geometric_context: True
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_frames_all_cams_annotated_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v3' # Where the models will be saved
    monitor: 'abs_rel' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
