arch:
    max_epochs: 24
model:
    checkpoint_path: '/home/users/vbelissen/saved_models_v3/default_config-fisheye_v2_config17-cam3-2021.05.27-14h19m08s/epoch=05_valeo_multiview-list_cam_3_frames_camera3annotated_test_sync_shuffled-velodyne-cam_3-abs_rel=0.208.ckpt'
    loss:
        supervised_method: 'sparse-abs_rel'
        mask_ego: False
        supervised_loss_weight: 0.005
    name: 'SemiSupModel_fisheye_valeo'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 2
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_3_frames_camera3annotated_train_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['cam_3']]
        repeat: [1]
        with_geometric_context: False
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_3_frames_camera3annotated_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['cam_3']]
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_3_frames_camera3annotated_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['cam_3']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v3' # Where the models will be saved
    monitor: 'abs_rel' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
