arch:
    max_epochs: 20
model:
    checkpoint_path: '/home/users/vbelissen/saved_models_v2/default_config-fisheye_v2_multiview_cam0_eval_Valeo-geometric_context-2021.05.12-18h02m00s/epoch=19_valeo_multiview-list_cam_0_annotated_frames_test_sync_shuffled-velodyne-cam_0-abs_rel_pp_gt=0.933.ckpt'
    name: 'SelfSupModel_fisheye_valeo'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 150.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 1
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_full_train_shuffled.txt']
        depth_type: ['']
        cameras: [['cam_0']]
        repeat: [1]
        with_geometric_context: True
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_annotated_frames_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['cam_0']]
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_annotated_frames_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['cam_0']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v2' # Where the models will be saved
    monitor: 'abs_rel_pp_gt' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
