arch:
    max_epochs: 20
model:
    loss:
        mask_ego: True
    name: 'SelfSupModel_fisheye_valeo_testPose'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 150.0
datasets:
    augmentation:
        image_shape: (160, 256)
    train:
        batch_size: 32
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_frames_camera0annotated_train_shuffled.txt']
        depth_type: ['']
        cameras: [['cam_0']]
        repeat: [1]
        with_geometric_context: True
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_annotated_frames_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['cam_0']]
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_0_annotated_frames_test_sync_shuffled.txt']
        depth_type: ['velodyne']
        cameras: [['cam_0']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v2' # Where the models will be saved
    monitor: 'abs_rel_pp_gt' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
