arch:
    max_epochs: 30
model:
    checkpoint_path: '/home/users/vbelissen/saved_models_v4/default_config-LR-A-semisup-fromSemi-008-depth200-2021.10.26-15h47m49s/epoch=08_valeo_multiview-list_cam_4_frames_camera4annotated_test_sync_shuffled_dataset2viewsUS-velodyne-cam_4-abs_rel=0.087.ckpt'
    loss:
        mask_ego: True
        supervised_loss_weight: 0.15
    name: 'SemiSupModel_distorted'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet200'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 2
        dataset: ['KITTIValeoDistorted']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_4_frames_camera4annotated_train_shuffled_dataset2viewsUS.txt']
        depth_type: ['velodyne']
        cameras: [['cam_4']]
        repeat: [1]
        with_geometric_context: False
    validation:
        dataset: ['KITTIValeoDistorted']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_4_frames_camera4annotated_test_sync_shuffled_dataset2viewsUS.txt']
        depth_type: ['velodyne']
        cameras: [['cam_4']]
    test:
        dataset: ['KITTIValeoDistorted']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_cam_4_frames_camera4annotated_test_sync_shuffled_dataset2viewsUS.txt']
        depth_type: ['velodyne']
        cameras: [['cam_4']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v4' # Where the models will be saved
    monitor: 'abs_rel' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
