arch:
    max_epochs: 20
model:
    loss:
        mask_ego: True
        photometric_reduce_op: 'min'
        automask_loss: True
        pose_consistency_translation_loss_weight: 0.1
        pose_consistency_rotation_loss_weight: 0.1
    name: 'SelfSupModel_multifocal'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (160, 256)
    train:
        batch_size: 2
        dataset: ['ValeoMultifocal']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_toy_multifocal_test_sync.txt']
        depth_type: ['']
        cameras: [['mixed']]
        repeat: [1]
        with_geometric_context: True
        with_spatiotemp_context: True
    validation:
        dataset: ['ValeoMultifocal']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_toy_multifocal_test_sync.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
    test:
        dataset: ['ValeoMultifocal']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_toy_multifocal_test_sync.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v3' # Where the models will be saved
    monitor: 'abs_rel_gt' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
