arch:
    max_epochs: 10
model:
    name: 'VelSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 200.0
datasets:
    augmentation:
        image_shape: (192, 320)
    train:
        batch_size: 1
        dataset: ['DGP']
        path: ['/home/vbelissen/Downloads/DDAD_tiny/ddad_tiny.json']
        split: ['train']
        depth_type: ['lidar']
        cameras: [['camera_01', 'camera_05']]
        repeat: [10]
    validation:
        dataset: ['DGP']
        path: ['/home/vbelissen/Downloads/DDAD_tiny/ddad_tiny.json']
        split: ['train']
        depth_type: ['lidar']
        cameras: [['camera_01']]
    test:
        dataset: ['DGP']
        path: ['/home/vbelissen/Downloads/DDAD_tiny/ddad_tiny.json']
        split: ['train']
        depth_type: ['lidar']
        cameras: [['camera_01']]
checkpoint:
    save_top_k: 0
    filepath: '/home/vbelissen/Downloads/temp_saved_models' # Where the models will be saved
    monitor: 'abs_rel_gt' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
