arch:
    max_epochs: 20
model:
    loss:
        mask_ego: True
    name: 'SelfSupModel_fisheye_CamConvs'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthCAMResNet'
        version: '18pt'
    pose_net:
        name: 'PoseCAMResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 40.0
datasets:
    augmentation:
        image_shape: (800, 1280)
    train:
        batch_size: 2
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_test2.txt']
        depth_type: ['']
        cameras: [['mixed']]
        repeat: [1]
        with_geometric_context: False
        cam_convs: True
    validation:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_test2.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
        cam_convs: True
    test:
        dataset: ['KITTIValeoFisheye']
        path: ['/home/data/vbelissen/valeo_multiview']
        split: ['list_test2.txt']
        depth_type: ['velodyne']
        cameras: [['mixed']]
        cam_convs: True
checkpoint:
    save_top_k: 0
    filepath: '/home/users/vbelissen/saved_models_v3' # Where the models will be saved
    monitor: 'abs_rel_gt' # which metric is observed
    monitor_index: 0 # from which validation dataset the metric is observed
    mode: 'min' # if the metric is minimized or maximized
